-- MySQL Script generated by MySQL Workbench
-- Mon May 27 00:23:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema compliment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compliment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compliment` DEFAULT CHARACTER SET utf8 ;
USE `compliment` ;

-- -----------------------------------------------------
-- Table `compliment`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compliment`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `useremail` VARCHAR(45) NOT NULL,
  `userpass` VARCHAR(255) NOT NULL,
  `validationCode` VARCHAR(45) NOT NULL,
  `activationStatus` TINYINT(1) NOT NULL DEFAULT 0,
  `age` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `height` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `goal` VARCHAR(45) NULL DEFAULT 'no goal',
  `metabolism` VARCHAR(45) NULL,
  `vitamins` VARCHAR(45) NULL,
  `magnesium` VARCHAR(45) NULL,
  `screentime` VARCHAR(45) NULL DEFAULT 'false',
  `smoking` VARCHAR(45) NULL DEFAULT 'false',
  `sleephrs` VARCHAR(45) NULL,
  `allergies` VARCHAR(255) NULL DEFAULT '[]',
  `diet` VARCHAR(255) NULL DEFAULT '[]',
  `healthcomplications` VARCHAR(500) NULL DEFAULT '[]',
  `pastprescriptions` VARCHAR(500) NULL DEFAULT 'false',
  `newrescriptions` VARCHAR(500) NULL DEFAULT '[]',

  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compliment`.`compliments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compliment`.`compliments` (
  -- `idcompliments` INT NOT NULL AUTO_INCREMENT,
  `complimentname` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `counterFlags` VARCHAR(255) NULL DEFAULT 'safe',
  `prise` VARCHAR(45) NULL DEFAULT '0000000',
  `tempsprise` VARCHAR(45) NULL DEFAULT '08:00 AM',
  `picture` VARCHAR(255) NULL DEFAULT NULL)
  
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compliment`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compliment`.`doctors` (
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compliment`.`astuces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compliment`.`astuces` (
 
  `astuce` VARCHAR(255) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compliment`.`questions_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compliment`.`questions_reference` (
  `idquestions` INT NOT NULL,
  `question` VARCHAR(255) NULL,
  `categorie` VARCHAR(45) NULL,
  `supplementconcerne` VARCHAR(45) NULL,
  `answears` VARCHAR(500) NULL,
  PRIMARY KEY (`idquestions`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
